version: '3'
services:
  waitfordb:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres
    command: postgres:5432

  postgres:
    image: postgres:12.3-alpine
    environment:
      TZ                  : ${TZ}
      POSTGRES_USER       : 'user'
      POSTGRES_PASSWORD   : 'password'
      POSTGRES_DB         : "bookshelf"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    hostname: postgres
    restart: always

  api:
    build: ./api
    depends_on:
      - postgres
      - waitfordb
    environment:
      API_PORT       : ${API_PORT}
      API_DB_HOST    : ${API_DB_HOST}
      API_DB_PORT    : ${API_DB_PORT}
      API_DB_USER    : ${API_DB_USER}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_DB_NAME    : ${API_DB_NAME}
      TZ             : ${TZ}
    command:
      - "sh"
      - "-c"
      - "go run ./cmd/bookshelf/main.go"
    working_dir: /api
    volumes:
      - ./api:/api
    hostname: api
    restart: always

  nginx:
    image: nginx:1.19-alpine
    depends_on:
      - api
    ports:
        - "${NGINX_PORT}:${API_PORT}"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./frontend/build:/public
    restart: always

volumes:
  postgres:
