
// Objective-C API for talking to the following Go packages
//
//	github.com/Ppang0405/bookshelf/mobile-epub-reader
//
// File is generated by gomobile bind. Do not edit.
#ifndef __EpubReader_FRAMEWORK_H__
#define __EpubReader_FRAMEWORK_H__

#include "Epubreader.objc.h"
#include "Universe.objc.h"

#endif
